---
- include: pki.yml
  when: gitlab_config_enable_https|default(false)

- name: create backup dir
  become: yes
  become_user: root
  when: gitlab_config_manage_backup_path|default(false) or gitlab_config_backup_upload_nfs|default(false)
  file:
    path: '{{gitlab_config_backup_dir}}'
    state: directory
    mode: 0755
    owner: git
    group: git

- name: load gitlab-config file
  become: yes
  become_user: root
  register: load_config
  template:
    src: gitlab.rb.j2
    dest: '{{gitlab_config_dest}}/gitlab.rb'
    mode: 0600

- name: reconfigure gitlab
  become: yes
  become_user: root
  when: gitlab_config_reconfigure|default(true) and load_config|changed
  command: gitlab-ctl reconfigure

- include: backup.yml
  when: gitlab_config_auto_nightly_backup | default(true)
